version: '3'
services:
  tripvote-db:
    container_name: tripvote-db
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 30s
      retries: 3
    networks:
      - network
  tripvote-redis:
    container_name: tripvote-redis
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    networks:
      - network
networks:
  network: