## 구글 PlaceAPI - 검색 결과 아이템의 id를 받아 리뷰로 반환
### 숙소
GET http://localhost:8080/test/review?textQuery=서울 중구 동호로 249

### 축제
GET http://localhost:8080/test/review?textQuery=얼음나라화천 산천어축제

## 리뷰 Biz
### 리뷰 생성
POST http://localhost:8080/reviews
Content-Type: application/json

{
  "placeId": 2714406,
  "contentTypeId": 32,
  "title" : "신라스테이 서부산",
  "areaCode": 1,
  "rating": 3,
  "content": "굿굿44",
  "images": [
    "http://tong.visitkorea.or.kr/cms/resource/01/3023101_image2_1.jpg",
    "http://tong.visitkorea.or.kr/cms/resource/09/3023109_image2_1.jpg"
  ],
  "visitedAt": "2024-01-04"
}

### 리뷰 수정
PATCH http://localhost:8080/reviews
Content-Type: application/json


{
  "reviewId" : 1,
  "rating" : 5,
  "content" : "다시 생각해보니 별점 5점",
  "images" : [
    "http://tong.visitkorea.or.kr/cms/resource/01/3023101_image2_1.jpg",
    "http://tong.visitkorea.or.kr/cms/resource/09/3023109_image2_1.jpg"
  ],
  "visitedAt": "2024-01-01"
}

### 리뷰 삭제
DELETE http://localhost:8080/reviews/1

### 상세 페이지 리뷰 조회 (리뷰 개수+ 별점 제외)
GET http://localhost:8080/reviews?page=0&size=10
Content-Type: application/json

{
  "placeId" : 2807380,
  "placeTitle" : "감자밭",
  "contentTypeId": 39
}

### 내가 쓴 리뷰 조회
GET http://localhost:8080/reviews/my

### 장소에 대한 리뷰 개수 및 별점 조회
GET http://localhost:8080/reviews/rating
Content-Type: application/json

{
  "placeId" : 2807380,
  "placeTitle" : "감자밭",
  "contentTypeId": 39
}
