spring:
  config:
    activate:
      on-profile: dev

  devtools:
    livereload:
      enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:4406/tripvote?characterEncoding=UTF-8
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: localhost
      port: 6379

cors:
  allowed-origins: http://localhost:3000,http://localhost:5173,http://localhost:5174

jwt:
  secret-key: d9xfFo5p73CTZ346fGq3quGiHpUyCi/0rA0ti7bwHAP7da9oTa3eXCpSxrZBDF+s
  access-token-name: access-token
  access-token-authentication-property: authentication
  access-token-authorities-property: authorities
  access-token-expire-time: 1000000
  access-token-cookie-expire-time: 1000000
  refresh-token-name: refresh-token
  refresh-token-expire-time: 1000000
  refresh-token-cookie-expire-time: 1000000
  issuer: tripvote-1

domain: localhost:8080