### 리뷰 작성
POST http://localhost:8080/reviews
Content-Type: application/json

{
  "placeId": {{placeId}},
  "contentTypeId": {{contentTypeId}},
  "title": "{{title}}",
  "rating": {{rating}},
  "content": "{{content}}",
  "images": {{images}},
  "visitedAt": "{{visitedAt}}"
}

### 리뷰 수정
PATCH http://localhost:8080/reviews
Content-Type: application/json

{
  "reviewId": {{reviewId}},
  "rating": {{rating}},
  "content": "{{content2}}",
  "images": {{images}},
  "visitedAt": "{{visitedAt}}"
}

### 리뷰 삭제
DELETE http://localhost:8080/reviews/1

### 해당 장소 리뷰 조회
GET http://localhost:8080/reviews?placeId={{placeId}}&contentTypeId={{contentTypeId}}&placeTitle={{title}}

### 리뷰 평점 및 총 개수 조회
GET http://localhost:8080/reviews/rating?
    placeId={{placeId}}&contentTypeId={{contentTypeId}}&placeTitle={{title}}